### ISSUE TITLE
Could not resolve "./index_bg.wasm"

### ISSUE THREAD

**Issue by mimoo** [cloudflare/rustwasm-worker-template#41]
using  wrangler 3.4.0, wasm-pack 0.12.1, and this template.

```
✘ [ERROR] Could not resolve "./index_bg.wasm"

    index_bg.js:1:22:
      1 │ import * as wasm from './index_bg.wasm';
        ╵                       ~~~~~~~~~~~~~~~~~

1 error
Error: esbuild exited with status exit status: 1

✘ [ERROR] Command failed with exit code 1: cargo install -q worker-build && worker-build --release
```

note that the template had a bunch of warnings so following them this is what I ended up with as `wrangler.toml`:

```toml
name = "..."
workers_dev = true
compatibility_date = "2022-01-20"
main = "build/worker/shim.mjs"

[vars]
WORKERS_RS_VERSION = "0.0.9"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
```

**Comment by mimoo** [comment]
<img width="243" alt="Screenshot 2023-08-02 at 10 42 01 AM" src="https://github.com/cloudflare/rustwasm-worker-template/assets/1316043/eb6d619e-dea1-41e4-92a9-22b736f82dac">

^ maybe it should import `index.wasm`?

**Comment by mimoo** [comment]
I realized something weird, when I run `wrangler dev` it will actually produce `build/index_bg.wasm` but will then delete it

**Comment by mimoo** [comment]
found a work around in https://github.com/cloudflare/workers-rs/issues/310

change the build command in `wrangler.toml` to downgrade wrangler:

```toml
[build]
command = "cargo install -q worker-build --version ^0.0.8 && worker-build --release" # required
```
